# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: add-images-gulp CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - run: npm install
    - run: |
        sudo add-apt-repository ppa:dhor/myway
        sudo apt-get update
        sudo apt-get install graphicsmagick
    - run: gulp
   
    - run: | 
        git config --global user.email "bot@gmail.com"
        git config --global user.name "bot"
        git add .
        git commit -m "Convert JPEG"
        git push
