# This is a basic workflow to help you get started with Actions

name: Update from Instagram

# Controls when the workflow will run
on: issue_comment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get:
    name: Get Post from Instagram
    if: ${{ !github.event.issue.pull_request }} && ${{ github.event.issue.number == 1 }} && ${{ github.event.issue.user.login == swiftlysingh }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Hell YA!
        env:
          NUMBER: ${{ github.event.issue.number }}
          AUTHOR: ${{ github.event.issue.user.login }}
          CONTEXT: ${{ toJson(github) }}
